
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_title = true
history = 10000
multiplier = 3
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 19
y = 19

[keyboard.bindings]
action = "ToggleFullscreen"
key = "F11"

[general]
live_config_reload = true
import = [
    "/home/gabriel/.config/alacritty/colors.toml",
    "/home/gabriel/.config/alacritty/fonts.toml",
]
